version: '3'
services:
  rest-api:
    build: .
    ports:
      - 3000:3000
    hostname: api-kino-rest-service
    env_file: .env
    volumes:
      - ./:/app
      - /app/node_modules
    # depends_on:
    #   - postgresql
  postgresql:
    image: postgres:latest  
    ports:
      - 5433:5432
    hostname: db-kino-rest-service
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/:ro