FROM node:latest
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn

COPY tsconfig.json ./
COPY src ./src

RUN npx prisma generate

RUN yarn run build
CMD [ "yarn", "run", "start:prod" ]

EXPOSE 3000